# Generated by Django 3.0.3 on 2021-02-19 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_title', models.CharField(max_length=30)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', related_query_name='reminder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
