# Generated by Django 3.0.3 on 2021-02-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0002_auto_20210220_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_status',
            new_name='reminder_active',
        ),
    ]
