# Generated by Django 3.0.3 on 2021-02-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0003_auto_20210220_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='user',
            new_name='owner',
        ),
    ]
