# Generated by Django 3.0.3 on 2021-02-23 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0005_auto_20210223_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 17, 2, 46, 187460)),
        ),
    ]
