# Generated by Django 3.0.3 on 2021-02-23 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0006_auto_20210223_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 0)),
        ),
    ]
