# Generated by Django 3.0.3 on 2021-02-23 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0009_auto_20210223_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 19, 45, 44, 446970)),
        ),
    ]
