# Generated by Django 3.0.3 on 2021-02-24 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0011_auto_20210223_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 8, 54, 19, 803568)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 9, 4, 19, 803568)),
        ),
    ]
