# Generated by Django 3.0.3 on 2021-02-24 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminders', '0012_auto_20210224_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 11, 2, 4, 687008)),
        ),
    ]
